import QtQuick 2.0

ListModel
{
    ListElement
    {
        text: "Africa"
        data: [
            ListElement { text:"Abidjan" },
            ListElement { text:"Accra" },
            ListElement { text:"Addis_Ababa" },
            ListElement { text:"Algiers" },
            ListElement { text:"Asmara" },
            ListElement { text:"Bamako" },
            ListElement { text:"Bangui" },
            ListElement { text:"Banjul" },
            ListElement { text:"Bissau" },
            ListElement { text:"Blantyre" },
            ListElement { text:"Brazzaville" },
            ListElement { text:"Bujumbura" },
            ListElement { text:"Cairo" },
            ListElement { text:"Casablanca" },
            ListElement { text:"Ceuta" },
            ListElement { text:"Conakry" },
            ListElement { text:"Dakar" },
            ListElement { text:"Dar_es_Salaam" },
            ListElement { text:"Djibouti" },
            ListElement { text:"Douala" },
            ListElement { text:"El_Aaiun" },
            ListElement { text:"Freetown" },
            ListElement { text:"Gaborone" },
            ListElement { text:"Harare" },
            ListElement { text:"Johannesburg" },
            ListElement { text:"Juba" },
            ListElement { text:"Kampala" },
            ListElement { text:"Khartoum" },
            ListElement { text:"Kigali" },
            ListElement { text:"Kinshasa" },
            ListElement { text:"Lagos" },
            ListElement { text:"Libreville" },
            ListElement { text:"Lome" },
            ListElement { text:"Luanda" },
            ListElement { text:"Lubumbashi" },
            ListElement { text:"Lusaka" },
            ListElement { text:"Malabo" },
            ListElement { text:"Maputo" },
            ListElement { text:"Maseru" },
            ListElement { text:"Mbabane" },
            ListElement { text:"Mogadishu" },
            ListElement { text:"Monrovia" },
            ListElement { text:"Nairobi" },
            ListElement { text:"Ndjamena" },
            ListElement { text:"Niamey" },
            ListElement { text:"Nouakchott" },
            ListElement { text:"Ouagadougou" },
            ListElement { text:"Porto-Novo" },
            ListElement { text:"Sao_Tome" },
            ListElement { text:"Tripoli" },
            ListElement { text:"Tunis" },
            ListElement { text:"Windhoek" }
        ]
    }
    ListElement
    {
        text: "America"
        data: [
            ListElement { text:"Adak" },
            ListElement { text:"Anchorage" },
            ListElement { text:"Anguilla" },
            ListElement { text:"Antigua" },
            ListElement { text:"Araguaina" },
            ListElement { text:"Argentina/Buenos_Aires" },
            ListElement { text:"Argentina/Catamarca" },
            ListElement { text:"Argentina/Cordoba" },
            ListElement { text:"Argentina/Jujuy" },
            ListElement { text:"Argentina/La_Rioja" },
            ListElement { text:"Argentina/Mendoza" },
            ListElement { text:"Argentina/Rio_Gallegos" },
            ListElement { text:"Argentina/Salta" },
            ListElement { text:"Argentina/San_Juan" },
            ListElement { text:"Argentina/San_Luis" },
            ListElement { text:"Argentina/Tucuman" },
            ListElement { text:"Argentina/Ushuaia" },
            ListElement { text:"Aruba" },
            ListElement { text:"Asuncion" },
            ListElement { text:"Atikokan" },
            ListElement { text:"Bahia" },
            ListElement { text:"Bahia_Banderas" },
            ListElement { text:"Barbados" },
            ListElement { text:"Belem" },
            ListElement { text:"Belize" },
            ListElement { text:"Blanc-Sablon" },
            ListElement { text:"Boa_Vista" },
            ListElement { text:"Bogota" },
            ListElement { text:"Boise" },
            ListElement { text:"Cambridge_Bay" },
            ListElement { text:"Campo_Grande" },
            ListElement { text:"Cancun" },
            ListElement { text:"Caracas" },
            ListElement { text:"Cayenne" },
            ListElement { text:"Cayman" },
            ListElement { text:"Chicago" },
            ListElement { text:"Chihuahua" },
            ListElement { text:"Costa_Rica" },
            ListElement { text:"Creston" },
            ListElement { text:"Cuiaba" },
            ListElement { text:"Curacao" },
            ListElement { text:"Danmarkshavn" },
            ListElement { text:"Dawson" },
            ListElement { text:"Dawson_Creek" },
            ListElement { text:"Denver" },
            ListElement { text:"Detroit" },
            ListElement { text:"Dominica" },
            ListElement { text:"Edmonton" },
            ListElement { text:"Eirunepe" },
            ListElement { text:"El_Salvador" },
            ListElement { text:"Fortaleza" },
            ListElement { text:"Glace_Bay" },
            ListElement { text:"Godthab" },
            ListElement { text:"Goose_Bay" },
            ListElement { text:"Grand_Turk" },
            ListElement { text:"Grenada" },
            ListElement { text:"Guadeloupe" },
            ListElement { text:"Guatemala" },
            ListElement { text:"Guayaquil" },
            ListElement { text:"Guyana" },
            ListElement { text:"Halifax" },
            ListElement { text:"Havana" },
            ListElement { text:"Hermosillo" },
            ListElement { text:"Indiana/Indianapolis" },
            ListElement { text:"Indiana/Knox" },
            ListElement { text:"Indiana/Marengo" },
            ListElement { text:"Indiana/Petersburg" },
            ListElement { text:"Indiana/Tell_City" },
            ListElement { text:"Indiana/Vevay" },
            ListElement { text:"Indiana/Vincennes" },
            ListElement { text:"Indiana/Winamac" },
            ListElement { text:"Inuvik" },
            ListElement { text:"Iqaluit" },
            ListElement { text:"Jamaica" },
            ListElement { text:"Juneau" },
            ListElement { text:"Kentucky/Louisville" },
            ListElement { text:"Kentucky/Monticello" },
            ListElement { text:"Kralendijk" },
            ListElement { text:"La_Paz" },
            ListElement { text:"Lima" },
            ListElement { text:"Los_Angeles" },
            ListElement { text:"Lower_Princes" },
            ListElement { text:"Maceio" },
            ListElement { text:"Managua" },
            ListElement { text:"Manaus" },
            ListElement { text:"Marigot" },
            ListElement { text:"Martinique" },
            ListElement { text:"Matamoros" },
            ListElement { text:"Mazatlan" },
            ListElement { text:"Menominee" },
            ListElement { text:"Merida" },
            ListElement { text:"Metlakatla" },
            ListElement { text:"Mexico_City" },
            ListElement { text:"Miquelon" },
            ListElement { text:"Moncton" },
            ListElement { text:"Monterrey" },
            ListElement { text:"Montevideo" },
            ListElement { text:"Montserrat" },
            ListElement { text:"Nassau" },
            ListElement { text:"New_York" },
            ListElement { text:"Nipigon" },
            ListElement { text:"Nome" },
            ListElement { text:"Noronha" },
            ListElement { text:"North_Dakota/Beulah" },
            ListElement { text:"North_Dakota/Center" },
            ListElement { text:"North_Dakota/New_Salem" },
            ListElement { text:"Ojinaga" },
            ListElement { text:"Panama" },
            ListElement { text:"Pangnirtung" },
            ListElement { text:"Paramaribo" },
            ListElement { text:"Phoenix" },
            ListElement { text:"Port-au-Prince" },
            ListElement { text:"Port_of_Spain" },
            ListElement { text:"Porto_Velho" },
            ListElement { text:"Puerto_Rico" },
            ListElement { text:"Rainy_River" },
            ListElement { text:"Rankin_Inlet" },
            ListElement { text:"Recife" },
            ListElement { text:"Regina" },
            ListElement { text:"Resolute" },
            ListElement { text:"Rio_Branco" },
            ListElement { text:"Santa_Isabel" },
            ListElement { text:"Santarem" },
            ListElement { text:"Santiago" },
            ListElement { text:"Santo_Domingo" },
            ListElement { text:"Sao_Paulo" },
            ListElement { text:"Scoresbysund" },
            ListElement { text:"Sitka" },
            ListElement { text:"St_Barthelemy" },
            ListElement { text:"St_Johns" },
            ListElement { text:"St_Kitts" },
            ListElement { text:"St_Lucia" },
            ListElement { text:"St_Thomas" },
            ListElement { text:"St_Vincent" },
            ListElement { text:"Swift_Current" },
            ListElement { text:"Tegucigalpa" },
            ListElement { text:"Thule" },
            ListElement { text:"Thunder_Bay" },
            ListElement { text:"Tijuana" },
            ListElement { text:"Toronto" },
            ListElement { text:"Tortola" },
            ListElement { text:"Vancouver" },
            ListElement { text:"Whitehorse" },
            ListElement { text:"Winnipeg" },
            ListElement { text:"Yakutat" },
            ListElement { text:"Yellowknife" }
        ]
    }
    ListElement
    {
        text: "Antarctica"
        data: [
            ListElement { text:"Casey" },
            ListElement { text:"Davis" },
            ListElement { text:"DumontDUrville" },
            ListElement { text:"Macquarie" },
            ListElement { text:"Mawson" },
            ListElement { text:"McMurdo" },
            ListElement { text:"Palmer" },
            ListElement { text:"Rothera" },
            ListElement { text:"Syowa" },
            ListElement { text:"Troll" },
            ListElement { text:"Vostok" }
        ]
    }
    ListElement
    {
        text: "Arctic"
        data: [
            ListElement { text:"Longyearbyen" }
        ]
    }
    ListElement
    {
        text: "Asia"
        data: [
            ListElement { text:"Aden" },
            ListElement { text:"Almaty" },
            ListElement { text:"Amman" },
            ListElement { text:"Anadyr" },
            ListElement { text:"Aqtau" },
            ListElement { text:"Aqtobe" },
            ListElement { text:"Ashgabat" },
            ListElement { text:"Baghdad" },
            ListElement { text:"Bahrain" },
            ListElement { text:"Baku" },
            ListElement { text:"Bangkok" },
            ListElement { text:"Beirut" },
            ListElement { text:"Bishkek" },
            ListElement { text:"Brunei" },
            ListElement { text:"Choibalsan" },
            ListElement { text:"Chongqing" },
            ListElement { text:"Colombo" },
            ListElement { text:"Damascus" },
            ListElement { text:"Dhaka" },
            ListElement { text:"Dili" },
            ListElement { text:"Dubai" },
            ListElement { text:"Dushanbe" },
            ListElement { text:"Gaza" },
            ListElement { text:"Harbin" },
            ListElement { text:"Hebron" },
            ListElement { text:"Ho_Chi_Minh" },
            ListElement { text:"Hong_Kong" },
            ListElement { text:"Hovd" },
            ListElement { text:"Irkutsk" },
            ListElement { text:"Jakarta" },
            ListElement { text:"Jayapura" },
            ListElement { text:"Jerusalem" },
            ListElement { text:"Kabul" },
            ListElement { text:"Kamchatka" },
            ListElement { text:"Karachi" },
            ListElement { text:"Kashgar" },
            ListElement { text:"Kathmandu" },
            ListElement { text:"Khandyga" },
            ListElement { text:"Kolkata" },
            ListElement { text:"Krasnoyarsk" },
            ListElement { text:"Kuala_Lumpur" },
            ListElement { text:"Kuching" },
            ListElement { text:"Kuwait" },
            ListElement { text:"Macau" },
            ListElement { text:"Magadan" },
            ListElement { text:"Makassar" },
            ListElement { text:"Manila" },
            ListElement { text:"Muscat" },
            ListElement { text:"Nicosia" },
            ListElement { text:"Novokuznetsk" },
            ListElement { text:"Novosibirsk" },
            ListElement { text:"Omsk" },
            ListElement { text:"Oral" },
            ListElement { text:"Phnom_Penh" },
            ListElement { text:"Pontianak" },
            ListElement { text:"Pyongyang" },
            ListElement { text:"Qatar" },
            ListElement { text:"Qyzylorda" },
            ListElement { text:"Rangoon" },
            ListElement { text:"Riyadh" },
            ListElement { text:"Sakhalin" },
            ListElement { text:"Samarkand" },
            ListElement { text:"Seoul" },
            ListElement { text:"Shanghai" },
            ListElement { text:"Singapore" },
            ListElement { text:"Taipei" },
            ListElement { text:"Tashkent" },
            ListElement { text:"Tbilisi" },
            ListElement { text:"Tehran" },
            ListElement { text:"Thimphu" },
            ListElement { text:"Tokyo" },
            ListElement { text:"Ulaanbaatar" },
            ListElement { text:"Urumqi" },
            ListElement { text:"Ust-Nera" },
            ListElement { text:"Vientiane" },
            ListElement { text:"Vladivostok" },
            ListElement { text:"Yakutsk" },
            ListElement { text:"Yekaterinburg" },
            ListElement { text:"Yerevan" }
        ]
    }
    ListElement
    {
        text: "Atlantic"
        data: [
            ListElement { text:"Azores" },
            ListElement { text:"Bermuda" },
            ListElement { text:"Canary" },
            ListElement { text:"Cape_Verde" },
            ListElement { text:"Faroe" },
            ListElement { text:"Madeira" },
            ListElement { text:"Reykjavik" },
            ListElement { text:"South_Georgia" },
            ListElement { text:"Stanley" },
            ListElement { text:"St_Helena" }
        ]
    }
    ListElement
    {
        text: "Australia"
        data: [
            ListElement { text:"Adelaide" },
            ListElement { text:"Brisbane" },
            ListElement { text:"Broken_Hill" },
            ListElement { text:"Currie" },
            ListElement { text:"Darwin" },
            ListElement { text:"Eucla" },
            ListElement { text:"Hobart" },
            ListElement { text:"Lindeman" },
            ListElement { text:"Lord_Howe" },
            ListElement { text:"Melbourne" },
            ListElement { text:"Perth" },
            ListElement { text:"Sydney" }
        ]
    }
    ListElement
    {
        text: "Europe"
        data: [
            ListElement { text:"Amsterdam" },
            ListElement { text:"Andorra" },
            ListElement { text:"Athens" },
            ListElement { text:"Belgrade" },
            ListElement { text:"Berlin" },
            ListElement { text:"Bratislava" },
            ListElement { text:"Brussels" },
            ListElement { text:"Bucharest" },
            ListElement { text:"Budapest" },
            ListElement { text:"Busingen" },
            ListElement { text:"Chisinau" },
            ListElement { text:"Copenhagen" },
            ListElement { text:"Dublin" },
            ListElement { text:"Gibraltar" },
            ListElement { text:"Guernsey" },
            ListElement { text:"Helsinki" },
            ListElement { text:"Isle_of_Man" },
            ListElement { text:"Istanbul" },
            ListElement { text:"Jersey" },
            ListElement { text:"Kaliningrad" },
            ListElement { text:"Kiev" },
            ListElement { text:"Lisbon" },
            ListElement { text:"Ljubljana" },
            ListElement { text:"London" },
            ListElement { text:"Luxembourg" },
            ListElement { text:"Madrid" },
            ListElement { text:"Malta" },
            ListElement { text:"Mariehamn" },
            ListElement { text:"Minsk" },
            ListElement { text:"Monaco" },
            ListElement { text:"Moscow" },
            ListElement { text:"Oslo" },
            ListElement { text:"Paris" },
            ListElement { text:"Podgorica" },
            ListElement { text:"Prague" },
            ListElement { text:"Riga" },
            ListElement { text:"Rome" },
            ListElement { text:"Samara" },
            ListElement { text:"San_Marino" },
            ListElement { text:"Sarajevo" },
            ListElement { text:"Simferopol" },
            ListElement { text:"Skopje" },
            ListElement { text:"Sofia" },
            ListElement { text:"Stockholm" },
            ListElement { text:"Tallinn" },
            ListElement { text:"Tirane" },
            ListElement { text:"Uzhgorod" },
            ListElement { text:"Vaduz" },
            ListElement { text:"Vatican" },
            ListElement { text:"Vienna" },
            ListElement { text:"Vilnius" },
            ListElement { text:"Volgograd" },
            ListElement { text:"Warsaw" },
            ListElement { text:"Zagreb" },
            ListElement { text:"Zaporozhye" },
            ListElement { text:"Zurich" }
        ]
    }
    ListElement
    {
        text: "Indian"
        data: [
            ListElement { text:"Antananarivo" },
            ListElement { text:"Chagos" },
            ListElement { text:"Christmas" },
            ListElement { text:"Cocos" },
            ListElement { text:"Comoro" },
            ListElement { text:"Kerguelen" },
            ListElement { text:"Mahe" },
            ListElement { text:"Maldives" },
            ListElement { text:"Mauritius" },
            ListElement { text:"Mayotte" },
            ListElement { text:"Reunion" }
        ]
    }
    ListElement
    {
        text: "Pacific"
        data: [
            ListElement { text:"Apia" },
            ListElement { text:"Auckland" },
            ListElement { text:"Chatham" },
            ListElement { text:"Chuuk" },
            ListElement { text:"Easter" },
            ListElement { text:"Efate" },
            ListElement { text:"Enderbury" },
            ListElement { text:"Fakaofo" },
            ListElement { text:"Fiji" },
            ListElement { text:"Funafuti" },
            ListElement { text:"Galapagos" },
            ListElement { text:"Gambier" },
            ListElement { text:"Guadalcanal" },
            ListElement { text:"Guam" },
            ListElement { text:"Honolulu" },
            ListElement { text:"Johnston" },
            ListElement { text:"Kiritimati" },
            ListElement { text:"Kosrae" },
            ListElement { text:"Kwajalein" },
            ListElement { text:"Majuro" },
            ListElement { text:"Marquesas" },
            ListElement { text:"Midway" },
            ListElement { text:"Nauru" },
            ListElement { text:"Niue" },
            ListElement { text:"Norfolk" },
            ListElement { text:"Noumea" },
            ListElement { text:"Pago_Pago" },
            ListElement { text:"Palau" },
            ListElement { text:"Pitcairn" },
            ListElement { text:"Pohnpei" },
            ListElement { text:"Port_Moresby" },
            ListElement { text:"Rarotonga" },
            ListElement { text:"Saipan" },
            ListElement { text:"Tahiti" },
            ListElement { text:"Tarawa" },
            ListElement { text:"Tongatapu" },
            ListElement { text:"Wake" },
            ListElement { text:"Wallis" }
        ]
    }
}
